### PR TITLE
fix(hmr): modules from transpilers do not use the 'css-resource-plugin' (fixes #16)

### LINKED ISSUE #16: SCSS hot reload is not working
@EisenbergEffect thanks for doing the release, unfortunately the new feat in #12 doesn't seem to work for me. @niieani, @jods4 did you try it out at the time?

**I'm submitting a bug report**

* **Library Version:**
0.2.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Node Version:**
8.2.1

* **NPM Version:**
5.4.2

* **JSPM OR Webpack AND Version**
Webpack 3.6.0

* **Browser:**
Chrome 61.0.3163.100

* **Language:**
TypeScript 2.5.2

**Current behavior:**
All my dependencies are up to date

```json
{
  "version": "1.0.0",
  "sasslintConfig": "node_modules/siopa-package-tools/.sass-lint.yml",
  "private": true,
  "scripts": {
    "test": "jest",
    "start": "webpack"
  },
  "dependencies": {
    "aurelia-bootstrapper": "^2.1.1",
    "aurelia-dependency-injection": "^1.3.2",
    "aurelia-framework": "^1.1.5",
    "aurelia-pal": "^1.4.0",
    "aurelia-router": "^1.4.0"
  },
  "devDependencies": {
    "@types/extract-text-webpack-plugin": "^3.0.0",
    "@types/jest": "^21.1.2",
    "@types/node": "^8.0.32",
    "aspnet-webpack": "^2.0.1",
    "aurelia-hot-module-reload": "^0.2.0",
    "aurelia-polyfills": "^1.2.2",
    "aurelia-webpack-plugin": "^2.0.0-rc.5",
    "css-loader": "^0.28.7",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.5",
    "gulp": "github:gulpjs/gulp#4.0",
    "import-glob-loader": "^1.1.0",
    "node-sass": "^4.5.3",
    "sass-loader": "^6.0.6",
    "siopa-package-tools": "^1.0.9",
    "style-loader": "^0.19.0",
    "ts-loader": "^2.3.7",
    "ts-node": "^3.3.0",
    "tslib": "^1.7.1",
    "tslint": "^5.5.0",
    "typescript": "^2.5.2",
    "webpack": "^3.6.0",
    "webpack-hot-middleware": "^2.19.1"
  }
}
```

Given the following component, when changing the color, an error is displayed in console.
```js
// relevant webpack config line
{ test: /\.scss$/i, issuer: /\.html$/i, loader: 'css-loader!sass-loader' },
```

```html
<template class="c-header-bar">
  <require from="./header-bar.scss"></require>
  My Header Text
</template>
```

```scss
.c-header-bar {
  color: blue;
}
```

```
process-update.js:115 [HMR] Cannot check for update (Full reload needed)
handleError @ process-update.js:115
process-update.js:116 [HMR] TypeError: Cannot read property 'resources' of undefined
    at HmrContext.29.HmrContext.reloadCss (http://localhost:5000/dist/app.js?v=QNzl5O3zgddSQAkYZUauFSbxSVlDVeKMHEZPOYHMqfk:10355:29)
...ETC
handleError @ process-update.js:116
aurelia-hot-module-reload.js:235 Uncaught (in promise) TypeError: Cannot read property 'resources' of undefined
    at HmrContext.29.HmrContext.reloadCss (aurelia-hot-module-reload.js:235)
    at Object.hot (aurelia-hot-module-reload.js:79)
    at aurelia-loader-webpack.js:167
    at Object.hotApply [as apply] (bootstrap 8fa308dbf2e403c4d37c:580)
    at cb (process-update.js:52)
    at process-update.js:68
    at <anonymous>
```

**Expected/desired behavior:**

Given the following component, when changing the color, then the rendered text should change color without console errors.

If I use `.css` files instead with the same setup and following webpack config line everything works

```js
        { test: /\.css$/i, issuer: /\.html$/i, loader: 'css-loader' },
```

### PR DESCRIPTION
**Pull request by AdamWillden**
This fix works for me - I'll let you decide if it's the 'right' way to fix it.

### CODE REVIEW

**Comment by EisenbergEffect** [comment]
@niieani Thoughts on this PR?

File: src/aurelia-hot-module-reload.ts [hunk 1]
```diff
@@ -224,13 +224,16 @@ export class HmrContext {
       return; // first load
     }
 
-    const cssPluginModuleId = this.loader.applyPluginToUrl(moduleId, 'css-resource-plugin');
+    const extensionIndex = moduleId.lastIndexOf('.');
+    const moduleExtension = moduleId.substring(extensionIndex + 1);
+    const pluginName = `${moduleExtension}-resource-plugin`;
+    const cssPluginModuleId = this.loader.applyPluginToUrl(moduleId, pluginName);
```
Comment (niieani) [inline src/aurelia-hot-module-reload.ts:230]: If such a plugin doesn't exist, it would be good to throw a meaningful error to the user, otherwise it might be confusing.

Rest should be fine.

**Review by niieani — CHANGES_REQUESTED** [review]

File: src/aurelia-hot-module-reload.ts (hunk 1 above)
Comment (AdamWillden) [reply src/aurelia-hot-module-reload.ts:230]: @niieani, there is no way to ask the loader if it is 'aware' of a plugin. I will make a change to check if the `analyzedModule` as specified by `cssPluginModuleId` is undefined and report an error for that so at least it's not a `Cannot read property 'resources' of undefined` error

Comment (niieani) [reply src/aurelia-hot-module-reload.ts:230]: ok

Comment (kayle) [reply src/aurelia-hot-module-reload.ts:230]: @niieani Is this blocked on anything? I can't tell if the naming convention would for for stylus .styl files or not.

Comment (niieani) [reply src/aurelia-hot-module-reload.ts:230]: @kayle just waiting for extra check from @AdamWillden and we can merge this as a workaround for the moment.

Comment (AdamWillden) [reply src/aurelia-hot-module-reload.ts:230]: @niieani @kayle sorry for the delay. Note the additional friendly error check in the latest fixup commit:

```diff
+    if (typeof analyzedModule === 'undefined') {
+      console.error(`Unable to find module, check the plugin exists and the module has been loaded with the expected plugin`);
+      return;
+    } else 
```

Comment (niieani) [reply src/aurelia-hot-module-reload.ts:230]: @EisenbergEffect would we want to use `aurelia-logger` here instead of `console`?

Comment (AdamWillden) [reply src/aurelia-hot-module-reload.ts:230]: @niieani IIRC none of the errors use `aurelia-logger` - I copied how the existing errors are handled.

I would argue that is out of scope of this PR and should be tackled in it's own right.

**Comment by AdamWillden** [comment]
@EisenbergEffect I think this package is [missing from your list](https://github.com/aurelia/hot-module-reload/pull/12#issuecomment-334619302) of packages to check for releases

Can you make a release for this?

**Comment by EisenbergEffect** [comment]
I've got it added now. Should go out this weekend. I apologize! My life has been a little crazy the last few months. Working on stabilizing that now.

**Comment by AdamWillden** [comment]
@EisenbergEffect there's no need to apologise! Just wanted to bring this to your attention. I figured you must have a list :-) Life's typically more crazy than not in my experience!
